### PR TITLE
Fix elog format string for 32bit architectures

### PR DESCRIPTION
**Pull request by rascalDan**

### CODE REVIEW

**Comment by ringerc** [comment]
Same issue and solution as https://github.com/2ndQuadrant/bdr/pull/272

**Comment by ringerc** [comment]
In future, please provide descriptive commit messages.

**Comment by ringerc** [comment]
... and thanks very much for the fix!

**Comment by rascalDan** [comment]
Old habits of keeping it brief, will keep that in mind (I'll look at some others for guidelines) and no problem :-)

**Comment by ringerc** [comment]
>
> Old habits of keeping it brief, will keep that in mind (I'll look at some
> others for guidelines) and no problem :-)
>
>
Our own commits are not always the best model I'm afraid, since we're often
working under pressure and discussing things internally.

Where possible I try to follow the model set by PostgreSQL core, with
descriptive commit messages.

Please feel free to submit anything you find useful, in the end. Docs
included. Any input and help is always welcome, and details like commit
messages are minor. The only reason I mentioned this time is that it took
me longer to figure out why the change was needed and correct because there
wasn't much description.

**Pull request merged**
