### PR TITLE
GH #152 pglogical.alter_node_drop_interface allow to drop used interface

### PR DESCRIPTION
**Pull request by brushtyler**
Do not drop interface used in an existent subscription

### CODE REVIEW

**Comment by brushtyler** [comment]
Please note that this pull request refer REL2_x_STABLE branch because I've tested it on PostgreSQL10.

**Comment by ringerc** [comment]
master isn't really active; REL2_x_STABLE is where to work. I'll overwrite master with current REL2_x_STABLE now to reduce confusion. Done.

**Comment by ringerc** [comment]
Thanks very much. Sorry it took so long to get to this.

**Comment by brushtyler** [comment]
Thanks @ringerc

**Pull request merged**
